name: dart_case_bot
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Your Name <email@example.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  nyxx:
    git:
      url: git://github.com/l7ssha/nyxx.git
      ref: backend_rework
  sembast: ^1.9.3
  hex: ^0.1.2
