import 'package:dart_case_bot/collection.dart';
import 'package:dart_case_bot/skin.dart';
import 'package:dart_case_bot/rarity.dart';
import 'package:dart_case_bot/weapons.dart' as weapons;

RarityCollection knife =
    RarityCollection(rarity: Rarity.covert, percentage: 0.26 / 100, skins: [
  //Navaja
  Skin(
    name: "★ (Vanilla)",
    weapon: weapons.navaja,
    rarity: Rarity.covert,
    possiblewear: [1.0, 1.0],
    percentage: 1 / (4 * 13),
  ),
  Skin(
    name: "Fade",
    weapon: weapons.navaja,
    rarity: Rarity.covert,
    possiblewear: [0.0, 0.08],
    percentage: 1 / (4 * 13),
  ),
  Skin(
    name: "Crimson Web",
    weapon: weapons.navaja,
    rarity: Rarity.covert,
    possiblewear: [0.06, 0.8],
    percentage: 1 / (4 * 13),
  ),
  Skin(
    name: "Slaughter",
    weapon: weapons.navaja,
    rarity: Rarity.covert,
    possiblewear: [0.01, 0.26],
    percentage: 1 / (4 * 13),
  ),
  Skin(
    name: "Blue Steel",
    weapon: weapons.navaja,
    rarity: Rarity.covert,
    possiblewear: [0.0, 1.0],
    percentage: 1 / (4 * 13),
  ),
  Skin(
    name: "Stained",
    weapon: weapons.navaja,
    rarity: Rarity.covert,
    possiblewear: [0.0, 1.0],
    percentage: 1 / (4 * 13),
  ),
  Skin(
    name: "Case Hardened",
    weapon: weapons.navaja,
    rarity: Rarity.covert,
    possiblewear: [0.0, 1.0],
    percentage: 1 / (4 * 13),
  ),
  Skin(
    name: "Urban Masked",
    weapon: weapons.navaja,
    rarity: Rarity.covert,
    possiblewear: [0.06, 0.8],
    percentage: 1 / (4 * 13),
  ),
  Skin(
    name: "Night Stripe",
    weapon: weapons.navaja,
    rarity: Rarity.covert,
    possiblewear: [0.06, 0.8],
    percentage: 1 / (4 * 13),
  ),
  Skin(
    name: "Boreal Forest",
    weapon: weapons.navaja,
    rarity: Rarity.covert,
    possiblewear: [0.06, 0.8],
    percentage: 1 / (4 * 13),
  ),
  Skin(
    name: "Forest DDPAT",
    weapon: weapons.navaja,
    rarity: Rarity.covert,
    possiblewear: [0.06, 0.8],
    percentage: 1 / (4 * 13),
  ),
  Skin(
    name: "Scorched",
    weapon: weapons.navaja,
    rarity: Rarity.covert,
    possiblewear: [0.06, 0.8],
    percentage: 1 / (4 * 13),
  ),
  Skin(
    name: "Safari Mesh",
    weapon: weapons.navaja,
    rarity: Rarity.covert,
    possiblewear: [0.06, 0.8],
    percentage: 1 / (4 * 13),
  ),
//Stiletto
  Skin(
    name: "★ (Vanilla)",
    weapon: weapons.stiletto,
    rarity: Rarity.covert,
    possiblewear: [1.0, 1.0],
    percentage: 1 / (4 * 13),
  ),
  Skin(
    name: "Fade",
    weapon: weapons.stiletto,
    rarity: Rarity.covert,
    possiblewear: [0.0, 0.08],
    percentage: 1 / (4 * 13),
  ),
  Skin(
    name: "Crimson Web",
    weapon: weapons.stiletto,
    rarity: Rarity.covert,
    possiblewear: [0.06, 0.8],
    percentage: 1 / (4 * 13),
  ),
  Skin(
    name: "Slaughter",
    weapon: weapons.stiletto,
    rarity: Rarity.covert,
    possiblewear: [0.01, 0.26],
    percentage: 1 / (4 * 13),
  ),
  Skin(
    name: "Blue Steel",
    weapon: weapons.stiletto,
    rarity: Rarity.covert,
    possiblewear: [0.0, 1.0],
    percentage: 1 / (4 * 13),
  ),
  Skin(
    name: "Stained",
    weapon: weapons.stiletto,
    rarity: Rarity.covert,
    possiblewear: [0.0, 1.0],
    percentage: 1 / (4 * 13),
  ),
  Skin(
    name: "Case Hardened",
    weapon: weapons.stiletto,
    rarity: Rarity.covert,
    possiblewear: [0.0, 1.0],
    percentage: 1 / (4 * 13),
  ),
  Skin(
    name: "Urban Masked",
    weapon: weapons.stiletto,
    rarity: Rarity.covert,
    possiblewear: [0.06, 0.8],
    percentage: 1 / (4 * 13),
  ),
  Skin(
    name: "Night Stripe",
    weapon: weapons.stiletto,
    rarity: Rarity.covert,
    possiblewear: [0.06, 0.8],
    percentage: 1 / (4 * 13),
  ),
  Skin(
    name: "Boreal Forest",
    weapon: weapons.stiletto,
    rarity: Rarity.covert,
    possiblewear: [0.06, 0.8],
    percentage: 1 / (4 * 13),
  ),
  Skin(
    name: "Forest DDPAT",
    weapon: weapons.stiletto,
    rarity: Rarity.covert,
    possiblewear: [0.06, 0.8],
    percentage: 1 / (4 * 13),
  ),
  Skin(
    name: "Scorched",
    weapon: weapons.stiletto,
    rarity: Rarity.covert,
    possiblewear: [0.06, 0.8],
    percentage: 1 / (4 * 13),
  ),
  Skin(
    name: "Safari Mesh",
    weapon: weapons.stiletto,
    rarity: Rarity.covert,
    possiblewear: [0.06, 0.8],
    percentage: 1 / (4 * 13),
  ),
]);
